


HWMNG_NO_CONFIG_FILE = 20
HWMNG_NO_CONFIG_SPECIFIED = 21
HWMNG_UNKNOWN_CONFIG_SPECIFIED = 22
HWMNG_INVALID_CONFIG_FORMAT = 22

HWMNG_DATABUS_FIN_ERROR = 30
HWMNG_FAILED_TO_LOAD_CONTROLLERS = 31

# yet to implement
HWMNG_CONTROLLER_FATAL = 40 # when a controller raises a fatal error
