"""
Container module for all alert codes. Each alert code is globally unique.

"""

# session manager related
INF_SESSION_CREATION_REQUEST = 100
INF_SESSION_CLOSURE_REQUEST = 110
INF_SESSION_CREATION_OK = 120
INF_SESSION_CLOSURE_OK = 130
INF_SESSION_CREATION_FAILED = 140
INF_SESSION_CLOSURE_FAILED = 150


# hw controller related
WRN_HW_CONTROLLER_WARNING = 160
ERR_HW_CONTROLLER_ERROR = 170
FTL_HW_CONTROLLER_FATAL = 180

# os alerts
FTL_CORE_PROC_CRASH = 200

ERR_NONCRITICAL_PROC_CRASH = 210