; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:head-firmware]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = az-delivery-devkit-v4
framework = arduino
monitor_speed = 115200

lib_deps = 
	adafruit/Adafruit PWM Servo Driver Library@^3.0.2
	braydenanderson2014/SimpleVector@^1.0.9
build_src_filter =
    -<*>
	+<head_controller/*>
    


[env:body-firmware]
platform = espressif8266
framework = arduino
board = d1_mini
upload_port = COM3
monitor_speed = 115200
upload_speed = 115200
build_flags = -D IGNORE_SERIAL_DEVICE_DEBUG_CODE
lib_extra_dirs = ~/Documents/Arduino/libraries
lib_deps = 
	arduinogetstarted/ezLED
	braydenanderson2014/Hashtable@^1.1.3

build_src_filter =
    -<*>
	+<body/*>

[env:serialtest-nano]
platform = atmelavr
board = ATmega328P
framework = arduino
lib_extra_dirs = ~/Documents/Arduino/libraries
upload_port = COM6
lib_deps = 
	arduinogetstarted/ezLED
	braydenanderson2014/Hashtable@^1.1.3

build_flags =
    -fstack-usage
    -Wstack-usage=128

build_src_filter =
    -<*>
	+<serial_test/*>

[platformio]
description = codice principale per il controllo del movimento di una testa animatronic

