; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
description = 
	"Project hosting all firmware for the animatronic hardware drivers. Interaction with drivers
	happens via serial, using the SerialDevice library."

[env:head-firmware]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = az-delivery-devkit-v4
framework = arduino
monitor_speed = 115200
lib_deps = 
	adafruit/Adafruit PWM Servo Driver Library@^3.0.2
	braydenanderson2014/SimpleVector@^1.0.9
build_src_filter = 
	-<*>
	+<head_controller/*>

[env:body-firmware]
platform = atmelavr
board = ATmega328P
framework = arduino
upload_port = COM6
monitor_speed = 115200
upload_speed = 115200
lib_extra_dirs = ~/Documents/Arduino/libraries
lib_deps = 
	arduinogetstarted/ezLED
	braydenanderson2014/Hashtable@^1.1.3
	waspinator/AccelStepper@^1.64
	gin66/FastAccelStepper@^1.2.5
build_src_filter = 
	-<*>
	+<body/*>

[env:serialtest-nano]
platform = atmelavr
board = ATmega328P
framework = arduino
upload_port = COM3
monitor_speed = 115200
upload_speed = 115200
lib_extra_dirs = ~/Documents/Arduino/libraries
lib_deps = 
	arduinogetstarted/ezLED
	braydenanderson2014/Hashtable@^1.1.3
	gin66/FastAccelStepper@^1.2.5
build_flags = 
	-fstack-usage
	-Wstack-usage=128
build_src_filter = 
	-<*>
	+<serial_test/*>

[env:status-panel]
platform = atmelavr
board = nanoatmega328
framework = arduino
upload_port = COM8
monitor_speed = 115200
upload_speed = 115200
lib_extra_dirs = ~/Documents/Arduino/libraries
lib_deps = 
	arduino-libraries/LiquidCrystal@^1.0.7
    stutchbury/EncoderButton@^1.0.7
	arduinogetstarted/ezLED @ ^1.0.1
build_src_filter = 
	-<*>
	+<status_panel/*>
