[project]
name = "animacharacter-pyclient"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pynng>=0.8.1",
    "pysafeudp",
    "requests>=2.32.5",
]

[tool.uv.sources]
pysafeudp = { path = "../shared_libs/pysafeudp", editable = true }
animacharacter-pyclient = { workspace = true, editable = true }

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.uv.workspace]
members = [
    ".",
]

[dependency-groups]
dev = [
    "animacharacter-pyclient",
]
#"pysafeudp" = { git = "https://github.com/franconepippone/animacharacter_dev_src", subdirectory = "src/shared_libs/pysafeudp" }