<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>orchestration</name>
  <version>0.0.0</version>
  <description>Handles orchestration of the whole ros2 system</description>
  <maintainer email="americo@gmail.com">americo</maintainer>
  <license>TODO: License declaration</license>

  <depend>rclpy</depend>
  <depend>diagnostic_updater</depend>
  <depend>diagnostic_aggregator</depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
