"""
In this file we define all alerts ids as python constants

"""

# session manager related
INF_SESSION_CREATION_REQUEST = 10
INF_SESSION_CLOSURE_REQUEST = 11
INF_SESSION_CREATION_OK = 12
INF_SESSION_CLOSURE_OK = 13
INF_SESSION_CREATION_FAILED = 14
INF_SESSION_CLOSURE_FAILED = 15
