[project]
name = "mcudrivers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Americo", email = "americo.cherubini2003@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pyserialdevice",
]

[project.scripts]
mcudrivers = "mcudrivers:main"

[build-system]
requires = ["uv_build>=0.9.21,<0.10.0"]
build-backend = "uv_build"

[tool.uv.sources]
pyserialdevice = { path = "../pySerialDevice", editable = true }
