from abc import ABC, abstractmethod

class BaseHardwareDriver(ABC):
    @abstractmethod
    def begin(self) -> bool: ...
    @abstractmethod
    def deinit(self) -> bool: ...
    @abstractmethod
    def flush(self) -> bool: ...